In [1]:
import numpy as np

In [2]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.array([21,2,3])

array([21,  2,  3])

In [5]:
np.array([[23,54,53],[23,235,2]])

array([[ 23,  54,  53],
       [ 23, 235,   2]])

In [6]:
type(a)

numpy.ndarray

In [9]:
np.eye(4,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [10]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
np.diag([1,23,45,3,5])

array([[ 1,  0,  0,  0,  0],
       [ 0, 23,  0,  0,  0],
       [ 0,  0, 45,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  5]])

In [17]:
np.linspace(1,40,4)

array([ 1., 14., 27., 40.])

In [18]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[0::2]

array([0, 2, 4, 6, 8])

In [20]:
b=a
np.shares_memory(a,b)

True

In [21]:
b=a.copy()
np.shares_memory(a,b)

False

In [22]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])